//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_exam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoExamDataBaseEntities : DbContext
    {
        private static DemoExamDataBaseEntities _context;
        public DemoExamDataBaseEntities()
            : base("name=DemoExamDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<IssuePoints> IssuePoints { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<OrderGoods> OrderGoods { get; set; }
        public static DemoExamDataBaseEntities GetContext() ///Метод GetContext, позволяющий возвращать данные из базы данных
        {
            if (_context == null) ///Если контекст пуст
                _context = new DemoExamDataBaseEntities(); ///Создание нового экземпляра контекста
            return _context; ///Возврат контекста
        }
    }
}
