//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderGoods = new HashSet<OrderGoods>();
        }
    
        public int Number { get; set; }
        public Nullable<int> ClientId { get; set; }
        public bool Compound { get; set; }
        public System.DateTime DateOfOrder { get; set; }
        public System.DateTime DateOfDelievery { get; set; }
        public int PointOfIssue { get; set; }
        public string ClientSNP { get; set; }
        public int CodeOfRecieving { get; set; }
        public string Status { get; set; }
    
        public virtual IssuePoints IssuePoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderGoods> OrderGoods { get; set; }
        public virtual Users Users { get; set; }
    }
}
