USE master
CREATE DATABASE DemoExamDataBase
GO
USE DemoExamDataBase
CREATE TABLE Users(
[Id] INT IDENTITY PRIMARY KEY,
[Role] NVARCHAR(25) NOT NULL,
[FullName] NVARCHAR(MAX) NOT NULL,
[Login] NVARCHAR(100) NOT NULL,
[Password] NVARCHAR(30) NOT NULL
) 

CREATE TABLE Goods(
[Id] INT IDENTITY PRIMARY KEY,
[Category] NVARCHAR(100) NOT NULL,
[Discount] INT NOT NULL,
[Discription] NVARCHAR(MAX) NOT NULL,
[GoodsImage] BIT NULL,
[Manufacture] NVARCHAR(100) NOT NULL,
[Name] NVARCHAR(100) NOT NULL,
[Price] INT NOT NULL
)

CREATE TABLE IssuePoints(
[CityIndex] INT PRIMARY KEY NOT NULL,
[CityName] NVARCHAR(100) NOT NULL,
[StreetName] NVARCHAR(100) NOT NULL,
[HouseNumber] INT NULL
)

CREATE TABLE Orders(
[Number] INT IDENTITY PRIMARY KEY,
[ClientId] INT NULL,
[Compound] BIT NOT NULL,
[DateOfOrder] DATETIME NOT NULL,
[DateOfDelievery] DATETIME NOT NULL,
[PointOfIssue] INT NOT NULL,
[ClientSNP] NVARCHAR(100) null,
[CodeOfRecieving] INT NOT NULL,
[Status] NVARCHAR(30) NOT NULL,
FOREIGN KEY(ClientID) REFERENCES Users(Id),
FOREIGN KEY(PointOfIssue) REFERENCES IssuePoints(CityIndex)
)

CREATE TABLE OrderGoods(
[Id] INT IDENTITY NOT NULL,
[OrderId] INT NOT NULL,
[GoodsId] INT NOT NULL,
[Count] INT NOT NULL,
FOREIGN KEY(GoodsId) REFERENCES Goods(Id),
FOREIGN KEY(OrderId) REFERENCES Orders(Number)
)